### ISSUE TITLE
Bug: Copy pasting keybinds do not work

### ISSUE THREAD

**Issue by alanlichen** [replit-discord/replit-desktop#109] opened 2021-02-04 16:01 UTC
When doing copy paste on windows, It does not work. Instead, it will move the cursor to the end of the program. In order to copy-paste, you have to right-click. This is only an issue with the electron version and not the web version.

**Comment by alanlichen** [comment] 2021-02-04 16:01
I may be able to include an image later

**Comment by alanlichen** [comment] 2021-02-04 16:18
I'm pretty sure this only happens with ace editor with javascript, but I am not 100% sure. I tested with python and I don't have this bug

**Comment by spotandjake** [comment] 2021-02-05 02:19
it is not a bug it is because we use an ipad user agent i will look iff there is any way i can fix this.

**Comment by spotandjake** [comment] 2021-02-05 03:14
okay from what i can tell it is only ctrl + v that doesnt work  and this is not a bug with the app this is something that has been dissabled in the code again i will  see if i can find a work arround but i have not found a good one tonight lol.

**Comment by JDOG787** [comment] 2021-02-05 05:12
I had this problem too

**Comment by spotandjake** [comment] 2021-02-05 05:13
Yah you will it is part of the code lol for ace onreplit I will see if I can work arround it

**Comment by alanlichen** [comment] 2021-02-10 22:20
Any updates?

**Comment by FunnyLamma** [comment] 2021-02-11 18:59
I'll check

**Comment by spotandjake** [comment] 2021-02-11 19:00
no it is not a bug it is the actual code we need to dissable it in the ace editor. frissyn is looking at plugins if they get that up and running we should be able to fix it properly

**Comment by FunnyLamma** [comment] 2021-02-11 19:21
oh ok, i keep working on the background process

**Comment by spotandjake** [comment] 2021-02-20 03:14
we probably wont fix this for a little while maybe v4 but probs not v3. as it requires a lot of reading through code.

**Comment by spotandjake** [comment] 2021-02-23 23:32
Fixed in V3.0.0 just got to wait for push more shortcuts will probs be introduced after release

**Closed** 2021-02-23 23:39 UTC
Labels: Merge Request, bug, enhancement, help wanted, wontfix
